Feature/home
caosJeong/amber_djnagogirls pull request #1
Opened 2021-04-30 08:42 UTC by caosJeong

장고걸스 튜토리얼 작업 내용입니다.
꾸다네 가족 소개 홈페이지
가족 구성원 목록 페이지, 가족 구성원 상세 페이지 , 가족 구성원 생성 페이지로 구성되어 있으며 
FBV가 아닌 CBV 형식으로 구현하였습니다.
장고 템플릿 기능 중 커스텀 필터를 추가 하여 구성원의 특징을 해쉬태그 형식으로 변환하는 기능도 추가 하였습니다.

2021-05-02 23:22 UTC, elijah74 commented on members/views.py
> +        members = self.member.objects.all().order_by('id')
@caosJeong // generic.ListView 로 변경해 보세요. 보다 손쉽게 출력 가능합니다.

2021-05-02 23:23 UTC, elijah74 commented on members/templatetags/boolean_to_str.py
> +def legs_hashtag_str(value):
@caosJeong // 파일명과 다른 함수가 포함되어 있는데  boolean_to_str.py 파일명을 공용으로 쓸 수 있는 이름으로 변경하는 것은 어떨까요?

2021-05-03 01:31 UTC, caosJeong commented on members/views.py
> +        members = self.member.objects.all().order_by('id')
generic.ListView 변경하였습니다.

2021-05-03 01:32 UTC, caosJeong commented on members/templatetags/boolean_to_str.py
> +def legs_hashtag_str(value):
boolean_to_str -> member_decorator.py 로 변경하였습니다.

2021-05-03 01:47 UTC, caosJeong commented
@elijah74 
코멘트 주신 내용을 적용하였습니다.
- listview 적용
- 멤버 커스텀 필터 파일명 변경 (boolean_to_str -> member_decorator.py)
꾸다네가족 구성원 추가화면 적용
꾸다네가족 구성원 추가 바로가기 링크 수정

2021-05-03 01:59 UTC, fabi-choi approved these changes
👍

2021-05-03 07:03 UTC, caosJeong commented
@elijah74
오전에 요청하신 코멘트 내역을 반영 하였습니다.
- listview 사용시 기본 값으로 설정(template_name, context_name등 django에서 지원하는 기본 값 사용)
- member_list.html에서 데이터가 없는 경우 분기 처리
- member_decorator.py에 구성원 목록에서 구성원을 블럭(기본 3명)으로 묶어 노출 하기 필터 생성

2021-05-03 07:15 UTC, fabi-choi approved these changes

2021-05-03 07:15 UTC, fabi-choi commented on conf/settings.py
> +    'django_extensions',
테스트

2021-05-03 07:41 UTC, londonkim commented on members/models.py
> +    legs_sub1_type = models.CharField(verbose_name=_('서브1 분류'), max_length=100, default='한국땅')
option 중에 blank와 null 설명가능할까요

2021-05-03 07:41 UTC, londonkim commented on members/templatetags/member_decorator.py
> +    content = '#{} #{} #{}'.format(value.legs_type, value.legs_sub1_type, value.legs_sub2_type)
fstring 찾아보시길

2021-05-03 07:43 UTC, londonkim commented on members/templatetags/member_decorator.py
> +def block_object_list(object_list, block_size=3):
object_list vs objects

2021-05-03 07:43 UTC, londonkim commented on members/urls.py
app_name은 없나요

2021-05-03 08:37 UTC, caosJeong commented on members/models.py
> +    legs_sub1_type = models.CharField(verbose_name=_('서브1 분류'), max_length=100, default='한국땅')
null은 DB 칼럼이 null 값을 가질것인지 아닌지를 정의를 하고 blank는 폼 유효성 검사에서 빈값을 허용할것인지를 정의하는 것으로 알고 있습니다.

2021-05-03 08:41 UTC, caosJeong commented on members/templatetags/member_decorator.py
> +    content = '#{} #{} #{}'.format(value.legs_type, value.legs_sub1_type, value.legs_sub2_type)
'#{} #{} #{}'.format(value.legs_type, value.legs_sub1_type, value.legs_sub2_type) 
=> f'#{value.legs_type} #{value.legs_sub1_type} #{value.legs_sub2_type}' 
수정하겠습니다. 감사합니다!

2021-05-03 08:50 UTC, caosJeong commented on members/templatetags/member_decorator.py
> +def block_object_list(object_list, block_size=3):
object_list를 사용한 이유는 generic.ListView에서 context 기본 변수 명이 object_list로 선언되어 사용을 하였습니다. 
object_list vs objects의 차이점에 대해서 좀더 공부하겠습니다. 감사합니다.

2021-05-03 09:04 UTC, caosJeong commented on members/urls.py
members/urls.py에 app_name= 'member'로 지정을 하고 
{ % url 'member:member_*'} 형식으로 수정하여 내일 오전에 반영하겠습니다.
감사합니다.

2021-05-03 23:57 UTC, caosJeong commented
꾸다네 가족 런던 PR 피드백 적용 하였습니다.
- member_decorator.py fstring 적용
- member app_name 지정

2021-05-04 00:22 UTC, londonkim approved these changes
👍

2021-05-04 00:28 UTC, elijah74 requested changes

2021-05-04 00:28 UTC, elijah74 commented on members/views.py
> +    queryset = Member.objects.all().order_by('id')  # Get 5 books containing the title war
@caosJeong // queryset 에 직접 넣는 코드 삭제 해 주세요.
ordering 이용 하세요.

2021-05-04 00:28 UTC, elijah74 commented on members/views.py
> +    context_object_name = 'members'  # your own name for the list as a template variable
@caosJeong // 다수를 이용하시는 구조인가요?
template 재사용성을 위해서 context_object_name 을 피하고 기본 값을 이용하세요.

2021-05-04 00:28 UTC, elijah74 commented on members/views.py
> +    success_url = "/home"
@caosJeong // success_url 을 절대 경로가 아니라 reverse() 이용해 보세요.
특히 get_success_url() 이용하시는 것을 추천 드립니다.

2021-05-04 00:28 UTC, elijah74 commented on members/templates/members/members_info.html
> +                <a href="{% url 'member_detail' pk=members.0.pk %}">
@caosJeong // template 에 for문 사용가능합니다.
굳이 손으로 한땀한땀 배열 번호 넣어서 쓸 이유가 있나요?

2021-05-04 00:28 UTC, elijah74 commented on members/templates/members/member_list.html
> +                {% for block_object in object_list.reverse|block_object_list:3 %}
@caosJeong // reverse 쓰시지 마시고 view에서 order by 이용하시면 될텐데요.

2021-05-04 00:28 UTC, elijah74 commented on members/views.py
> +    success_url = _('member_list')
@caosJeong // success_url 에 넣으신 값이 이상해요

2021-05-04 02:18 UTC, caosJeong commented on members/views.py
> +    queryset = Member.objects.all().order_by('id')  # Get 5 books containing the title war
ordering = ['id'] 적용 하였습니다.

2021-05-04 02:23 UTC, caosJeong commented on members/views.py
> +    success_url = _('member_list')
success_url 에 reverse를 하니 오류가 생겨  좀더 찾아보니 reverse_lazy를 사용하니 정상적으로 구동되어 둘의 차이점을 찾아보겠습니다.
신기하게도 get_success_url을 선언하고 reverse로 리턴값을 설정하니 또 정상적으로 되어서 둘의차이점을 찾아보겠습니다.!

2021-05-04 02:25 UTC, caosJeong commented
꾸다네 가족 데이빗 PR 반영
- members/views.py 에서 구성원을 추가 후 success_url -> def get_success_url로 변경
get_success_url로 하니 reverse가 적용 되는것을 확인
reverse_lazy 적용 과정에서 생기는 오류 수정
- conf.urls.py에 urlpatterns에 path로 하니 오류가 생겨서(ImproperlyConfigured URLConf ) url()로 변경하였습니다.
- 데이빗이 알려준 reverse를 적용하니 오류가 생겨 구글링을 한 결과 https://code.djangoproject.com/ticket/29102에 보니 django 버그라서 reverse가 안된건지 .. 아님 문법이 틀린건지 아직 자세히는 몰라 오후에 좀더 공부하겠습니다. get_success_url은 reverse 함수가 정상으로 되는것을 확인 했습니다.

2021-05-04 02:28 UTC, elijah74 commented on conf/urls.py
> +    url(r'^member/', include('members.urls')),
@caosJeong // include의 namespace 적용 해 보세요.

2021-05-04 04:27 UTC, caosJeong commented
꾸다네 가족 데이빗 PR 반영
- conf.urls, members.urls에 path로 원복 , include에 namespace 추가했습니다.

2021-05-04 04:30 UTC, elijah74 commented on members/views.py
> +class MemberAddView(generic.CreateView):
@caosJeong // form_class 어디 있나요?

2021-05-04 08:41 UTC, caosJeong commented
꾸다네 가족 데이빗 PR 반영
- 가족 구성원 추가/수정/삭제 시 form_class 적용
- 추가/수정시 validatior 적용
- 구성원 수정시 수정 불가 항목 적용 하였습니다.

2021-05-06 08:54 UTC, merged